[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.arweave-mainnet]
shard = "primary"
protocol = "arweave"
provider = [
  { label = "arweave-mainnet", details = { type = "firehose", url = "http://0.0.0.0:16042" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]